name: Python Script in Actions

on: push

jobs:

  python3runner:
    runs-on: windows-latest

    steps:

          
      - name: Install Python 3

        run: |
         choco uninstall python3 --no-progress
         choco install python3 --no-progress
      - uses: actions/checkout@v2

      - name: Run Python action
        run: |  
           cd D:\home\runner\work\${{ env.REPO }}\${{ env.REPO }}

           python3 workflow.py
        env:
         REPO: python-action



        
