name: Python Script in Actions

on: workflow_dispatch

jobs:

  python3runner:
    runs-on: windows-latest

    steps:

          
      - name: Install Python 3

        run: |
         choco uninstall python3 --no-progress
         choco install python3 --no-progress
      - run: |
         cd C:\
         git clone https://github.com/Tyler887/python-action target
         mkdir source\files
         copy source\files target
         cd target



        # and then
      - name: Wrap repository
        run: |
          cd C:\
          target\wrapper.ps1

      - name: Run Python action
        run: |  
           cd D:\home\runner\work\${{ env.REPO }}\${{ env.REPO }}

           python3 workflow.py
        env:
         REPO: python-action



        
