name: Python Script in Actions

on: workflow_dispatch

jobs:

  python3runner:
    runs-on: windows-latest

    steps:

          
      - name: Install Python 3

        run: |
         choco uninstall python3 --no-progress
         choco install python3 --no-progress
      - run: |
         cd C:\
         git clone https://github.com/Tyler887/python-action target
         mkdir source\files
         copy source\files target
         cd target
      - uses: actions/upload-artifact@v2
        with:
          name: python-action-repo
          path: https://github.com/Tyler887/python-action.git
          retention-days: 1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: python-action-repo
          path: C:\parsed


      - name: Wrap repository
        run: |
          cd C:\parsed
          wrapper.ps1

      - name: Run Python action
        run: |  
           cd D:\home\runner\work\${{ env.REPO }}\${{ env.REPO }}

           python3 workflow.py
        env:
         REPO: python-action



        
