name: Python Script in Actions

on: workflow_dispatch

jobs:

  python3runner:

    runs-on: windows-latest

    steps:

      - name: Install Python 3

        run: choco install python3 --no-progress

      - name: Upload python script

        uses: actions/upload-artifact@master

        with:

          path: https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO }}/raw/main/workflow.py

          name: Pythonfile

          if-no-files-found: error
        env:
          REPO_OWNER: Tyler887
          REPO: python-action

        

      - name: Download script

        uses: actions/download-artifact@master

        with:

          name: Pythonfile

          path: C:\

          

      - run: |

          cd C:\

          python3 workflow.py

        
