name: Python Script in Actions

on: workflow_dispatch

jobs:

  python3runner:
    runs-on: windows-latest

    steps:

          
      - name: Install Python 3

        run: |
         choco uninstall python3 --no-progress
         choco install python3 --no-progress
      - run: |
         git clone https://github.com/Tyler887/python-action target
         copy source\files target
         cd target
         git add .
         git diff-index --quiet HEAD || git commit -m "add wrapper"



        # and then
      - name: Wrap repository
        run: wrapper.ps1
        env:
         OWNER: Tyler887
         REPO: python-action
      - run: |  
          cd C:\${{ env.REPO }}\.git

          python3 workflow.py



        
