name: Python Script in Actions

on: workflow_dispatch

jobs:

  python3runner:
    runs-on: windows-latest

    steps:

          
      - name: Install Python 3

        run: |
         choco uninstall python3 --no-progress
         choco install python3 --no-progress
      



        # and then
      - name: Wrap repository
        run: .\wrapper.ps1
        env:
         OWNER: Tyler887
         REPO: python-action
      - run: |  
          cd C:\${{ env.REPO }}

          python3 workflow.py


        
