name: Python Script in Actions

on: workflow_dispatch

jobs:

  python3runner:

    runs-on: windows-latest

    steps:

      - name: Install Python 3

        run: |
         choco uninstall python3 --no-progress
         choco install python3 --no-progress

      - run: |
          cd C:\
          Invoke-WebRequest https://github.com/${{ env.OWNER }}/${{ env.REPO }}.git

        env:
          OWNER: Tyler887
          REPO: python-script


          

      - name: Run script

        run: |

          cd C:\${{ env.REPO }}

          python3 workflow.py

        
